### ISSUE TITLE
An issue when using Link and ScrollOverPack

### ISSUE THREAD

**Issue by kanmanus** [react-component/scroll-anim#11]
Hi there,

As I saw in your example, you fix the height of each section and that works great.
However, in my case, I cannot fix the height because my content will increase the height of the section when open in mobile device. 

If I don't use a ScrollOverPack, then it works fine, but I want to use it too.

I realize that the TweenOne elements will be not shown until I scroll to that section. That makes Link scroll to the wrong position.

Do you have any idea?

Best,

**Comment by jljsj33** [comment]
https://github.com/react-component/scroll-anim/pull/12

**Comment by jljsj33** [comment]
0.4.0

**Comment by jljsj33** [comment]
0.4.1

offsetTop={58} not is negative.
