### ISSUE TITLE
timeout in componentDidMount causes race condition for componentWillUnmount

### ISSUE THREAD

**Issue by cainvommars** [react-component/scroll-anim#13]
I'm experiencing issues with the removeEventListener call in componentWillUnmount of the ScrollParallax.js -> https://github.com/react-component/scroll-anim/blob/master/src/ScrollParallax.jsx#L65

It's sometimes failing to remove the eventListener by calling this function with an undefined this.eventType. 

After digging into it I found this timeout https://github.com/react-component/scroll-anim/blob/master/src/ScrollParallax.jsx#L43 delaying the adding of the addEventListener in componentDidMount while the componentWillUnmount is already called. 
 
Is there a reason for the timeout?

After removing the timeout locally my issue is gone. So I wonder if it can be removed. :)

**Comment by cainvommars** [comment]
Or am I doing something wrong here?

**Comment by jljsj33** [comment]
thx, 0.6.3 fix
