### ISSUE TITLE
Is it possible to avoid the "pop in" effect?

### ISSUE THREAD

**Issue by FallingSnow** [react-component/scroll-anim#15]
Is it possible to have the elements always in the DOM just hidden? That way they don't change the height of their parent element when the animate in.

**Comment by jljsj33** [comment]
user tween-one

**Comment by jljsj33** [comment]
```jsx
 <ScrollOverPack id="page3"
        hideProps={{ 1: { reverse: true } }}
      >
        <TweenOne
          className="demo"
          animation={{ y: 0, opacity: 1 }}
          key="1"
          style={{ transform: 'translateY(100px)', opacity: 0 }}
        />
      </ScrollOverPack>
```

**Comment by FallingSnow** [comment]
Got the same result.

For example, notice how on https://react-component.github.io/tween-one/examples/group.html the black code box moves down when the page loads. I want to avoid that.

Am I doing something wrong, I'm using rc-queue-anim?

**Comment by jljsj33** [comment]
Try `appear: false`

**Comment by FallingSnow** [comment]
Same result but now there is no animations. The elements just pop in.

**Comment by jljsj33** [comment]
I will add a appear to ·OverPack·...

**Comment by FallingSnow** [comment]
I rolled my own component, thank you though.
