### ISSUE TITLE
建议增加OverPack需要设置最小高度的提示

### ISSUE THREAD

**Issue by EngsShi** [react-component/scroll-anim#22]
OverPack默认不渲染子节点，导致默认高度只有0。如果底部节点没法将OverPack顶到“播放点”，整个控件将无法显示。
只有在特定场景才会出现，测试的时候很诡异。希望在OverPack的说明页面增加相关注意事项。

例如：
屏幕大小200，OverPack下方的控件高度20，播放点为0.5。
由于OverPack未渲染，所以高度是0，滚动到底部时距离底部20，只有0.1，无法触发OverPack的setState({show: true})。
至少需要设定OverPack高度最小值80，才能保证滚动到底部时能触发播放事件。

**Comment by jljsj33** [comment]
恩，，，这个是需要写下，很多人遇到这样的问题。。。你也可以 PR。。。谢谢。。。
