### ISSUE TITLE
OverPack设置滚动目标targetId无效

### ISSUE THREAD

**Issue by zhangquxi** [react-component/scroll-anim#27]
我的结构是

div id="home"
div id="wel"
Element:page0
ScrollOverPack:page1
ScrollOverPack:page2
/div
/div

设置了targetId=home后page1、2都不能显示出来，改成targetId=wel后可以显示，但是是一起出来的，动画不会随着滚动条变化，请问是怎么回事呢？

**Comment by jljsj33** [comment]
http://react-component.github.io/scroll-anim/examples/target.html

**Comment by jljsj33** [comment]
div 的高度设了吗？

**Comment by jljsj33** [comment]
照上面例子，如果还是不行，，麻烦提供下重现，https://codepen.io/jljsj33/pen/awrRzj
