### ISSUE TITLE
ScrollParallax 的 onUpdate 没有实现

### ISSUE THREAD

**Issue by mosaice** [react-component/scroll-anim#31]
Parallax 说明 中animation 有一个参数
```
onUpdate | function | - | 更新时回调, 返回 ease 的百分比
```

[代码中并没有实现这个接口](https://github.com/react-component/scroll-anim/blob/master/src/ScrollParallax.jsx#L78)

**Comment by jljsj33** [comment]
好的，，我加下。。谢谢
