### ISSUE TITLE
where is addScrollEvent?  IE10 console error 对象不支持"addScrollEvent"属性或方法

### ISSUE THREAD

**Issue by Irislm** [react-component/scroll-anim#35]
https://github.com/react-component/scroll-anim/blob/9bdc5d609728376aadef7a16c66c5c11431721be/src/ScrollOverPack.jsx#L52

**Comment by Irislm** [comment]
ScrollOverPack继承 ScrollElement，ScrollElement 有函数 addScrollEvent
https://github.com/react-component/scroll-anim/blob/9bdc5d609728376aadef7a16c66c5c11431721be/src/ScrollElement.jsx#L96

看起来是ScrollOverPack继承ScrollElement有问题，是吗？
浏览器版本： IE10/IE9

**Comment by Irislm** [comment]
@jljsj33  waiting for you reply, thanks!

**Comment by jljsj33** [comment]
https://github.com/react-component/scroll-anim/blob/master/src/EventDispatcher.js#L37 
有这个判断啊，，不科学，，，我空了再看下吧。。。谢谢

**Comment by Irislm** [comment]
I think maybe it's a babel compile issue
http://leonshi.com/2016/03/16/babel6-es6-inherit-issue-in-ie10/
