### ISSUE TITLE
引入OverPack和QueueAnim配合antd的dropdown组件在划出下拉菜单时也有动画，如何取消

### ISSUE THREAD

**Issue by GRAMMAC1** [react-component/scroll-anim#37]

**Comment by GRAMMAC1** [comment]
header的下拉菜单用的是antd的dropdown组件，在container部分用了overpack和queueanim，然后在header划出菜单时也出现了container部分的动画效果，如何取消这个动画

**Comment by jljsj33** [comment]
如果还不行，，请提供下重现 demo..https://codesandbox.io/s/mooo9oxmxx

**Comment by GRAMMAC1** [comment]
啊，对不起，是我自己写的动画影响的，不是antd和OverPack的问题，不好意思
