### ISSUE TITLE
Temporarily disable scroll animations?

### ISSUE THREAD

**Issue by mrcoles** [react-component/scroll-anim#43]
Is there any way to temporarily disable the scroll animations? I have a Chrome extension that lets people screenshot web pages and on sites using this library it generally catches things mid-animation. Usually, it does things like set transitions to 0, but I’m seeing that the animations here are all done by setting explicit transform values directly in javascript. I don’t see a way to achieve that with this library ([example site](https://ant.design/)).

**Comment by jljsj33** [comment]
There is no way to ban it for the time being.
