### ISSUE TITLE
ScrollOverPack使用问题

### ISSUE THREAD

**Issue by zaraYanChun** [react-component/scroll-anim#5]
在学习这个http://motion.ant.design/#/components/scroll-anim?_k=96uiqy时候，发现一个demo，滚屏展示动画的，http://react-component.github.io/scroll-anim/examples/scrollScreen.html 这个例子有点问题，操作如下：
页面加载后，点击 page1，page2，有时候最后点击 page0后，有时候点着点着，就页面无法向下滚动，麻烦问下这个问题该怎么排查

**Comment by jljsj33** [comment]
有没有报错，，，是什么系统下的？？
