### ISSUE TITLE
window undefined 

### ISSUE THREAD

**Issue by Harris-Liu** [react-component/scroll-anim#7]
exports["default"] = new EventDispatcher(window);
                                         ^
ReferenceError: window is not defined

when compile, render at server have no window object.

please do a check before use it. like this

if (typeof window !== 'undefined') {
  exports["default"] = new EventDispatcher(window);
} else {
  exports["default"] = new EventDispatcher();
}

**Comment by jljsj33** [comment]
提供下代码好吗？？

**Comment by jljsj33** [comment]
0.3.6
