### ISSUE TITLE
滚动不到指定位置

### ISSUE THREAD

**Issue by hanwenbo** [react-component/scroll-anim#74]
http://react-component.github.io/scroll-anim/examples/linkAsynchronous.html

http://react-component.github.io/scroll-anim/examples/link.html

![image](https://user-images.githubusercontent.com/5869741/112287250-2447d500-8cc7-11eb-8127-eaf23a5ea676.png)
![image](https://user-images.githubusercontent.com/5869741/112287918-ce276180-8cc7-11eb-97f1-b327fc21c6a4.png)
![image](https://user-images.githubusercontent.com/5869741/112287980-ded7d780-8cc7-11eb-8ead-7811ce508cf7.png)

**Comment by jljsj33** [comment]
看代码，，有 toShowHeight

**Comment by jljsj33** [comment]
看代码，，有 toShowHeight

**Comment by jljsj33** [comment]
![image](https://user-images.githubusercontent.com/6802825/112308068-ab537800-8cdc-11eb-9bc5-ab3022c055f3.png)

**Comment by hanwenbo** [comment]
哈哈 妥了 谢谢
